mutation UpdateCollection($id: ID!, $title: String, $description: String, $visibility: CollectionVisibilityEnum, $mode: CollectionModeEnum, $timed: Boolean, $kind: CollectionKindEnum, $accentColor: CollectionAccentColorEnum, $bgTreatment: CollectionBgTreatmentEnum, $titleFont: CollectionTitleFontEnum) {
  updateCollection(
    input: { id: $id, attrs: { title: $title, description: $description, visibility: $visibility, mode: $mode, timed: $timed, kind: $kind, accentColor: $accentColor, bgTreatment: $bgTreatment, titleFont: $titleFont } }
  ) {
    collection {
      id
      title
      description
      visibility
      mode
      timed
      kind
      accentColor
      bgTreatment
      titleFont
    }
    errors
  }
}
