name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Install packages
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Run tests
        run: npm run test:unit

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Setup Git Submodules
        run: git submodule update --init --recursive

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}